# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\workspace\github\pwc-tools\views\ui_files\about_info_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_appDateToolAbout(object):
    def setupUi(self, appDateToolAbout):
        appDateToolAbout.setObjectName("appDateToolAbout")
        appDateToolAbout.resize(438, 361)
        appDateToolAbout.setMinimumSize(QtCore.QSize(250, 250))
        appDateToolAbout.setMaximumSize(QtCore.QSize(500, 500))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(appDateToolAbout)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(appDateToolAbout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 418, 341))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(250, 250))
        self.label.setMaximumSize(QtCore.QSize(750, 750))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(358, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.okayAbout = QtWidgets.QPushButton(self.frame)
        self.okayAbout.setObjectName("okayAbout")
        self.gridLayout.addWidget(self.okayAbout, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(appDateToolAbout)
        QtCore.QMetaObject.connectSlotsByName(appDateToolAbout)

    def retranslateUi(self, appDateToolAbout):
        _translate = QtCore.QCoreApplication.translate
        appDateToolAbout.setWindowTitle(_translate("appDateToolAbout", "About App Date Tool"))
        self.label.setText(_translate("appDateToolAbout", "The App Date Tool was developed by GESTF. This is version..."))
        self.okayAbout.setText(_translate("appDateToolAbout", "Okay"))
