# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\GitHub\PWC-Prep-Tool\pwctool\ui_files\error_mesage_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ErrorMessageDialog(object):
    def setupUi(self, ErrorMessageDialog):
        ErrorMessageDialog.setObjectName("ErrorMessageDialog")
        ErrorMessageDialog.resize(364, 164)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ErrorMessageDialog.sizePolicy().hasHeightForWidth())
        ErrorMessageDialog.setSizePolicy(sizePolicy)
        ErrorMessageDialog.setMinimumSize(QtCore.QSize(364, 164))
        ErrorMessageDialog.setMaximumSize(QtCore.QSize(364, 164))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        ErrorMessageDialog.setFont(font)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ErrorMessageDialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(ErrorMessageDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 344, 144))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.okayError = QtWidgets.QPushButton(self.frame)
        self.okayError.setGeometry(QtCore.QRect(230, 90, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.okayError.setFont(font)
        self.okayError.setObjectName("okayError")
        self.errMsgLabel = QtWidgets.QLabel(self.frame)
        self.errMsgLabel.setGeometry(QtCore.QRect(16, 19, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.errMsgLabel.setFont(font)
        self.errMsgLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.errMsgLabel.setWordWrap(True)
        self.errMsgLabel.setObjectName("errMsgLabel")
        self.horizontalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(ErrorMessageDialog)
        QtCore.QMetaObject.connectSlotsByName(ErrorMessageDialog)

    def retranslateUi(self, ErrorMessageDialog):
        _translate = QtCore.QCoreApplication.translate
        ErrorMessageDialog.setWindowTitle(_translate("ErrorMessageDialog", "ERROR"))
        self.okayError.setText(_translate("ErrorMessageDialog", "OK"))
        self.errMsgLabel.setText(_translate("ErrorMessageDialog", "TextLabel"))
